GBillotey/Fractalshades

- src/fractalshades/core.py
- src/fractalshades/numpy_utils/xrange.py
- src/fractalshades/perturbation.py
Commented _quad_precision_taylor_shift_one as seems not the right way to address SA glitches.
> typo + unused code

- examples/run_flake.py
- install_from_local.sh
- src/fractalshades/__init__.py
- src/fractalshades/core.py
- src/fractalshades/models/mandelbrot.py
- src/fractalshades/numpy_utils/xrange.py
- src/fractalshades/perturbation.py
- src/fractalshades/settings.py
- src/fractalshades/utils.py
- tests/test_perturbation.py
Refactor call signature to prepare GUI integration
Now to run a simulation  one has to do:
f = Fractal(directory)
f.zoom(**kwargs)
f.prepare_calc(**params)
f.run()
To change the zoom simply
f.zoom(**kwargs)
f.run()
To change a calc param:
f.prepare_calc(**params)
f.run()
> Refactor call signature

- examples/run_interactive.py
- src/fractalshades/models/mandelbrot.py
- src/fractalshades/perturbation.py
- tests/test_perturbation.py
> Improved Newton to make the test pass again

- src/fractalshades/numpy_utils/local_test_numba_xr.py
- src/fractalshades/numpy_utils/numba_xr.py
> operator.mul for Xrange_polynomial_Type in numba

- MANIFEST.in
- examples/run_flake.py
- src/fractalshades/core.py
- src/fractalshades/models/perturbation_mandelbrot.py
- src/fractalshades/perturbation.py
- tests/known_fails/fail2.py
- tests/test_debug_tool.py
- tests/test_perturbation.py
> solved failing case 2

- tests/test_perturbation.py
Basic glitch correction tests based on Dinkydau's Flake + a former failing case (divergent reference)
> Added glitch correction tests

- src/fractalshades/gui/guimodel.py
- src/fractalshades/gui/model.py
> Added support for color type in GUI

- .github/workflows/doc-latest.yml
- dev_notes.txt
- examples/interactive_mode/run_interactive.py
Workaround to build doc on github runner
> User cmaps

- requirements.txt
- setup.cfg
- src/fractalshades/__init__.py
Change the requirements to avoid a conflict between numpy and numba versions.
> 20211101 release 2.3.2 commit

- docs/API/postproc.rst
- examples/interactive_mode/run_interactive.py
- Added the  `Fieldlines_pp` that was missing
- For the GUI explorer, set initial values to a more reasonable iteration number (15000) and precision.
> Typos in the doc

- docs/API/postproc/Fieldlines_pp.rst
Adding the .rest for field lines doc...
> Typos in the doc2

- examples/interactive_mode/run_interactive.py
- setup.py
- src/fractalshades/core.py
- src/fractalshades/data/LICENSE.txt
- src/fractalshades/gui/guimodel.py
- src/fractalshades/gui/model.py
- src/fractalshades/perturbation.py
> save/reload gui params - add gui view rotation option

- src/fractalshades/models/perturbation_mandelbrot.py
- src/fractalshades/perturbation.py
- tests/test_FP_loop.py
Improve code factorization between models
> Refactor cycle loop

- examples/colormaps/plot_cmaps.py
- setup.cfg
- src/fractalshades/colors/colormap_templates.py
- src/fractalshades/gui/guimodel.py
See
https://discuss.python.org/t/deprecating-importlib-resources-legacy-api/11386
https://docs.python.org/3/library/importlib.html#importlib.resources.files
> Use importlib traversable API

- examples/batch_mode/02-bulb_fieldlines1.py
> Example colormap tuning

- docs/getting_started.rst
- docs/index.rst
- docs/overview.rst
- examples/batch_mode/10-double_embedded_julia.py
- examples/batch_mode/11-run_perturbdeep.py
A few typo + document unskewing streched areas
> Documentation update

- .github/workflows/doc-latest.yml
Improving the documentation build 
- deploy the html doc in a separate repo (Fractalshades-doc)
- Stores & reuse the result of `doc/examples` between runs -> allows, if the source code has not been modified, to entirely skip the calculation
> Improved doc build

- tests/test_perturbation.py
"Process finished with exit code 137 (interrupted by signal 9: SIGKILL)"
> Attempt to avoid OOM durong tests

- CHANGELOG.rst
- src/fractalshades/__init__.py
- src/fractalshades/core.py
- src/fractalshades/gui/guimodel.py
- src/fractalshades/gui/guitemplates.py
This PR seems to solve the issue under Linux, need more datapoint under Windows before merging
Xref #118
> Proposed PR to solve crash issue for large images

- .github/workflows/build-windows_2.yml
- CHANGELOG.rst
Updating changelog + split win build in 2 parts (to keep artifact size within the limits)
> last mod for 1.0.3

- docs/getting_started.rst
Hello @GBillotey,
I got the project working in Mac M1. Added the documentation in the PR. Please review it.
> Fix for m1 mac

- docs/getting_started.rst
- docs/index.rst
- docs/overview.rst
> Update installation instructions

- src/fractalshades/core.py
Needed when successive plots with supersampling 'on' and interior is activated then desactivated
> Post-plot cleaning of _subset_hook attribute

- src/fractalshades/core.py
> np.bool -> bool

- src/fractalshades/core.py
Keep track of tiles computed in previous substeps
> Tile counter in case of calculation by substeps (large expmap)

- CHANGELOG.rst
- src/fractalshades/__init__.py
> 1.2.0 commit

- src/fractalshades/movie/movie.py
> add_stream expects an int not a str

- examples/movies/pan_movie/pan_script.py
Bugfix: updated movie example.
> 'export_frames' is deprecated, use 'export_frame'
